# Generated by Django 4.1.7 on 2023-03-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer_profile_alter_orderplaced_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_profile',
            old_name='product_image',
            new_name='image',
        ),
    ]
